.github/workflows/push.yml
Makefile
mloq/assets/templates/makefile.docker
mloq/assets/templates/pyproject.toml
mloq/assets/workflows/push-dist.yml
mloq/assets/workflows/push-python.yml
mloq/configuration/config_values.py
scripts/makefile.docker

Fix selection of default branch

---

.github/workflows/push.yml
mloq/assets/templates/README.md

closes https://github.com/FragileTech/ml-ops-quickstart/issues/39

Fix generated doc badge

---

.github/workflows/push.yml
mloq/assets/workflows/push-dist.yml
mloq/assets/workflows/push-python.yml

closes https://github.com/FragileTech/ml-ops-quickstart/issues/36

Fix workflow names

---

.github/workflows/push.yml
mloq/assets/workflows/push-dist.yml
mloq/assets/workflows/push-python.yml

closes https://github.com/FragileTech/ml-ops-quickstart/issues/37

Add bump version action

---

mloq/api.py

Fix **18** of https://github.com/FragileTech/ml-ops-quickstart/issues/33

Fix project name in generated files

---

.gitignore
README.md
docs/Makefile
docs/make.bat
docs/requirements-build.txt
docs/requirements-docs.txt
docs/source/__index.rst
docs/source/_autoapi_templates/index.rst
docs/source/conf.py
docs/source/guide/features.md
docs/source/guide/library.md
docs/source/guide/usage.md
docs/source/guide/welcome.md
docs/source/index.md
mloq/directories.py
mloq/templating.py

closes https://github.com/FragileTech/ml-ops-quickstart/issues/51

Add documentation pages

---

.github/workflows/push.yml
mloq/assets/workflows/push-python.yml

Enable "Test wheels" back

---

mloq/api.py
mloq/cli/main.py
mloq/config/logic.py
mloq/tests/cli/test_main.py
mloq/tests/config/test_logic.py
mloq/tests/conftest.py
requirements.txt
setup.py

Remove ruyaml dependency. Add cli test

---

.github/workflows/push.yml
mloq/assets/workflows/push-dist.yml
mloq/assets/workflows/push-python.yml

Update the GHA configs

---

mloq/cli/setup_cmd.py
mloq/config/generation.py
mloq/config/params.py

Refactor parameters definition

---

mloq/assets/templates/makefile.docker
mloq/directories.py
mloq/requirements.py
mloq/tests/cli/test_main.py
mloq/tests/test_api.py
mloq/tests/test_requirements.py
mloq/tests/test_workflows.py
scripts/makefile.docker

Improve test coverage

---

.github/workflows/push.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
docs/source/assets
mloq.yml
mloq/assets/static/mloq.yml
mloq/assets/templates/CONTRIBUTING.md
mloq/assets/templates/MIT_LICENSE
mloq/config/generation.py
mloq/config/params.py
mloq/tests/conftest.py
mloq/tests/mloq.yml

Check markdown files

---

.github/workflows/push.yml
Makefile
mloq.yml
mloq/assets/templates/Makefile

Dogfood Makefile

---

.github/workflows/push.yml
.gitignore
.pre-commit-config.yaml
WHAT_MLOQ_GENERATED.md
mloq.yml
mloq/api.py
mloq/assets/static/.gitignore
mloq/assets/static/.pre-commit-config.yaml
mloq/assets/templates/WHAT_MLOQ_GENERATED.md
mloq/assets/templates/pyproject.toml
mloq/assets/templates/setup.txt
mloq/files.py
mloq/requirements.py
mloq/templating.py
mloq/tests/conftest.py
mloq/tests/test_api.py
mloq/tests/test_requirements.py
mloq/tests/test_workflows.py
mloq/workflows.py
pyproject.toml
setup.py

Generate WHAT_MLOQ_GENERATED.md

---

.github/workflows/push.yml
WHAT_MLOQ_GENERATED.md
mloq.yml

Dogfood WHAT_MLOQ_GENERATED.md

---

.pre-commit-config.yaml
mloq/assets/static/.pre-commit-config.yaml

Include isort in pre-commit hooks

---

.github/workflows/push.yml
README.md
docs/source/guide/usage.md
mloq/assets/workflows/push-python.yml

Disable running tests on version bumps

---

mloq/tests/test_api.py

Fix the flaky test

---

mloq/api.py
mloq/assets/static/GPL_LICENSE
mloq/assets/templates/APACHE_LICENSE
mloq/cli/setup_cmd.py
mloq/config/generation.py
mloq/config/params.py
mloq/files.py

Allow choosing different licenses

---

.pre-commit-config.yaml
mloq/assets/requirements/dogfood.txt
mloq/assets/requirements/requirements-lint.txt
mloq/assets/static/.pre-commit-config.yaml
mloq/files.py
requirements-lint.txt
requirements.txt

Fix missing file descriptions

---

WHAT_MLOQ_GENERATED.md
mloq/config/logic.py
mloq/files.py
mloq/requirements.py
mloq/skeleton.py
mloq/templating.py
mloq/workflows.py

Fix ledger generation. Fix main to be a template

---

docs/Makefile
docs/requirements-docs.txt
docs/source/conf.py
mloq.yaml
src/mloq/assets/docs/conf.txt
src/mloq/assets/docs/makefile_docs.txt
src/mloq/assets/docs/requirements-docs.txt
src/mloq/commands/docs.py
tests/commands/test_docs.py

Update docs command: Notebook theme and better notebook support

---

.github/workflows/deploy-docs.yml

Add deploy docs workflow

---

docs/requirements-docs.txt
src/mloq/assets/docs/requirements-docs.txt

Fix docs requirements

---

.codecov.yml
.github/workflows/push.yml
src/mloq/assets/ci/push.yml
src/mloq/assets/project/.codecov.yml

Update codecov config

---

src/mloq/commands/setup.py

Fix interactive mode

---

.codecov.yml
.github/workflows/push.yml
Makefile
docs/source/conf.py
mloq.yaml
pyproject.toml
src/mloq/assets/mloq/mloq.yaml
src/mloq/assets/project/.codecov.yml
src/mloq/assets/shared/Makefile
src/mloq/assets/shared/pyproject.toml
src/mloq/commands/globals.py
src/mloq/commands/lint.py
src/mloq/commands/package.py

Improve package cmd
